import '../../api/posts/methods.js';
import '../../api/posts/hooks.js';
import '../../api/posts/server/publications.js';
import '../../api/villages/methods.js';
import '../../api/villages/server/publications.js';
import '../../api/notifications/methods.js';
import '../../api/notifications/server/publications.js';
import '../../api/comments/methods.js';
import '../../api/comments/server/publications.js';
import '../../api/inbox/methods.js';
import '../../api/inbox/server/publications.js';
import '../../api/users/methods.js';
import '../../api/server/publications.js';
import './user-config.js';
import './config.js';
import './useraccounts-configuration.js';
import './fixtures.js';
// Seo
import '../../api/seo/seo.js';