import '../../api/posts/methods.js';
import '../../api/posts/hooks.js';
import '../../api/posts/server/publications.js';
import '../../api/profiles/methods.js';
import '../../api/profiles/hooks.js';
import '../../api/profiles/server/publications.js';
import '../../api/villages/methods.js';
import '../../api/villages/server/publications.js';
import '../../api/notifications/methods.js';
import '../../api/notifications/server/publications.js';
import '../../api/comments/methods.js';
import '../../api/comments/hooks.js';
import '../../api/comments/server/publications.js';
import '../../api/inbox/methods.js';
import '../../api/inbox/server/publications.js';
import '../../api/users/methods.js';
import '../../api/server/publications.js';
import './user-config.js';
import './config.js';
import './useraccounts-configuration.js';
import './fixtures.js';
import './migrations.js';
// Seo
import '../../api/seo/seo.js';
// Emails
import '../../api/emails/emails.js';
import '../../api/emails/cron.js';
import '../../api/emails/server/publications.js';
import '../../api/emails/server/methods.js';

import './server-global.js';
